version: '3'

services:
  app:
    image: node:17-alpine3.14
    container_name: docsify_dev
    tty: true
    volumes:
      - ./src:/workspace
    working_dir: "/workspace"
    command: npm run dev
    ports:
      - 8080:3000
